### ISSUE TITLE
:group_id => [] 如何与前端结合使用的

### ISSUE THREAD

**Issue by hoppergee** [wokenqingtian/fullstack-notes#22]
class Admin::UsersController < AdminController

	def index
		@users = User.includes(:groups).all
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])

		if @user.update(user_params)
			redirect_to admin_users_path
		else
			render "edit"
		end
	end

	protected

	def user_params
		params.require(:user).permit(:email, :group_ids => [])
	end

end

**Comment by SegXiong** [comment]
目前ihower老师使用的方式有select_tag和check_box_tag两种能向后段传送数组的表单工具。
