### ISSUE TITLE
bin/setup 什么意思

### ISSUE THREAD

**Issue by hoppergee** [wokenqingtian/fullstack-notes#30]

**Comment by SegXiong** [comment]
感觉是效果bundle check 和 bundle install的组合，检查，安装配置环境

**Comment by hoppergee** [comment]
确实如你所说
看过的资料
https://robots.thoughtbot.com/bin-setup
每个rails项目的bin文件夹里都有setup/bundler/rake/rails/update/spring这几个文件
https://github.com/growthschool/rails-recipes/blob/master/bin/setup
这也应证了经常看到以前的教程别人都是运行bin/rake.....bin/rails......bin/......
时间上就是从这个bin里面的脚本作为开头
然后看一下rails与rake两个文件写的基本一样
也就为什么现在rails与rake是一样的。其原因就在此

**Comment by hoppergee** [comment]
我的总结
http://wokenqingtian-blog.logdown.com/posts/1980553-bin-setup-exploration
