### ISSUE TITLE
t.index ["user_id], name: "index_products_on_user_id"

### ISSUE THREAD

**Issue by hoppergee** [wokenqingtian/fullstack-notes#34]
这个后面的
`name: "index_products_on_user_id"`有什么用？

**Comment by SegXiong** [comment]
查了一下，命名可以修改成任意。 你贴上来的这个应该是默认的命名。
作用的话，应该只是个提示作用。你可以参考[这个](https://stackoverflow.com/questions/4601138/what-is-the-significance-of-the-index-name-when-creating-an-index-in-mysql)，虽然这个说的是mySQL，感觉应该是一样的。
